//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakoIoT.Device.LocalConfiguration
{
    
    internal partial class HtmlResources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((HtmlResources.manager == null))
                {
                    HtmlResources.manager = new System.Resources.ResourceManager("MakoIoT.Device.LocalConfiguration.HtmlResources", typeof(HtmlResources).Assembly);
                }
                return HtmlResources.manager;
            }
        }
        internal static string GetString(HtmlResources.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(HtmlResources.BinaryResources id)
        {
            return ((byte[])(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            index = -2501,
            exit = 19374,
            message = 25577,
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            bundle_css = 28596,
        }
    }
}
